Kresclevertec sprint 2
ClevertecFrontendLab/sprint2-clevertecKress pull request #1
Opened 2023-02-06 23:45 UTC by clevertecKress

Все тесты прошел на зеленую галочку

2023-02-06 23:48 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675727301/slider%20one%20foto%20768px.png)

2023-02-07 07:05 UTC, Ivan6813 requested changes

2023-02-07 07:05 UTC, Ivan6813 commented on src/pages/book/book-page.jsx
> +    const reviews = useSelector(state => state.bookPage.reviews)
проверь почему у тебя не влазит вся страница в скриншот. Проверь размеры блока на котором висит data-test-id, что бы она был на всю высоту
![msedge_oHopAEuper](https://user-images.githubusercontent.com/79784960/217171072-9afa3dc1-6366-4046-8797-9be878ab2262.png)

2023-02-07 07:05 UTC, Ivan6813 commented on src/pages/book/book-page.jsx
> +    return (
сделай карточку в соответствии с макетом, как-то кривенько она выглядит

![msedge_yTP7Y8xclB](https://user-images.githubusercontent.com/79784960/217171768-ca34fa47-2cda-4e58-ba60-178d834216c5.png)

2023-02-07 07:05 UTC, Ivan6813 commented on src/pages/book/book-page.jsx
> +                        <span>{categories[`${bookParam.categories}`][`${bookParam.id}`].name}</span>
кнопка бургер меню сплющилась, так быть не должно

![msedge_WLd6MkXZAK](https://user-images.githubusercontent.com/79784960/217171989-85c8322d-cbcc-4fff-be80-7aa921576cce.png)

2023-02-07 18:54 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675796087/slider%20one%20foto%20768px.png)

2023-02-07 19:23 UTC, Ivan6813 requested changes

2023-02-07 19:23 UTC, Ivan6813 commented on src/pages/content/layout-main-content.jsx
> +        <div className='wrapper'>
куда-то пропали картинки

![msedge_3T3VRzs1J0](https://user-images.githubusercontent.com/79784960/217343450-f797e13b-8c2d-418a-9b0c-14aa787c321e.png)

2023-02-07 19:23 UTC, Ivan6813 commented on src/pages/content/layout-main-content.jsx
> +                    <div className='mainContant__nav'>
бургер меню не по макету, верхняя часть не по макету и отступ от самой кнопки очень большой

![msedge_ie8vSP9aV5](https://user-images.githubusercontent.com/79784960/217343682-5f198233-12a8-4fbf-8164-17ec7ea6ce23.png)

2023-02-07 19:23 UTC, Ivan6813 commented on src/pages/content/layout-main-content.jsx
> +                        test_id_ruls='navigation-terms'
когда бургер меню открыто, то при клике вне бургер меню оно должно закрываться, у тебя оно остается открытым

![msedge_op3QP9CimT](https://user-images.githubusercontent.com/79784960/217343996-0d9a7429-4768-4e6f-9e12-b993a423a826.png)

2023-02-07 19:23 UTC, Ivan6813 commented on src/pages/content/layout-main-content.jsx
> +                </div>
так и не исправил то, что страница полностью не видна на скрине

![msedge_j6fy9g6Pn7](https://user-images.githubusercontent.com/79784960/217344295-f44253c3-895f-4a29-a876-6a6a55fbb939.png)

2023-02-07 19:23 UTC, Ivan6813 commented on src/pages/content/layout-main-content.jsx
> +        </div>
здесь по тесту в слайдере должно быть одно фото, а у тебя два

![msedge_i7QYVsbfk6](https://user-images.githubusercontent.com/79784960/217344448-d0d78eeb-9169-4c13-b80f-f2954472e01a.png)

2023-02-07 23:13 UTC, clevertecKress commented on src/pages/content/layout-main-content.jsx
> +                </div>
Извините, я что-то не совсем понял какая страница должна быть полностью видна на скрине, я подумал что хедер обрезает, так это я поправил.

2023-02-07 23:23 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675812190/slider%20one%20foto%20768px.png)

2023-02-08 06:10 UTC, Ivan6813 requested changes

2023-02-08 06:10 UTC, Ivan6813 commented on src/pages/book/book-page.jsx
> +                    </div>
страница не влезает в скрин я имею ввиду, что у тебя на скрине только верхняя часть страницы, а нужно что бы была вся страница целиком, так как в этом тесте проверяется открытие закрытие блока с комментариями, а у тебя его попросту не видно на скрине и я не могу знать работает или нет данный функционал.

![msedge_msKLyn2f87](https://user-images.githubusercontent.com/79784960/217448349-6673ea52-ce0b-4fdd-a7c0-3526edf937fa.png)

2023-02-08 06:10 UTC, Ivan6813 commented on src/pages/book/book-page.jsx
> +                    ? <div className='bookPage__content__rating_empty display__block_content__rating_empty'>
бургер меню должно закрываться, если клик происходит не по меню. Этот тест это и проверяет, он открывает твоё бургер меню, кликает вне этого меню и оно должно закрыться, а у тебя оно остается открытым

![msedge_jgu7I0W3po](https://user-images.githubusercontent.com/79784960/217448839-b0bf28cb-2423-4a53-9bac-2d7dacff02a3.png)

2023-02-08 06:10 UTC, Ivan6813 commented on src/pages/book/book-page.jsx
> +                    </div>
поправь немного верстку здесь, а то у тебя рейтинг прилип к картинке

![msedge_lmN5v9GZgj](https://user-images.githubusercontent.com/79784960/217449049-f698f4a7-89a6-4613-b97b-eab0fa2338da.png)

2023-02-08 06:27 UTC, clevertecKress commented on src/pages/book/book-page.jsx
> +                    </div>
Тест проверяет этот функционал, и выдал ответ что все работает, вы же видите что все тесты прошли на 100%

2023-02-08 06:30 UTC, clevertecKress commented on src/pages/book/book-page.jsx
> +                    </div>
Хорошо я сегодня вечером обязательно всё перепроверю ещё раз. Днём у меня к сожалению не получается Я работаю но вечером всё перепроверю и скину ещё один пуш

2023-02-08 06:40 UTC, clevertecKress commented on src/pages/book/book-page.jsx
> +                    </div>
Я кажется понял что вы имеете в виду, вечером сегодня переделаю, спасибо вам за правильные замечание.

2023-02-08 18:53 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 10.
Количество непройденных тестов: 0.
***
**app 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/app%20320px.png)
***
**app 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/app%20768px.png)
***
**app burger-menu close 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/app%20burger-menu%20close%20320px.png)
***
**app burger-menu close 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/app%20burger-menu%20close%20768px.png)
***
**app burger-menu close click not burger-menu 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/app%20burger-menu%20close%20click%20not%20burger-menu%20320px.png)
***
**app burger-menu close click not burger-menu 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/app%20burger-menu%20close%20click%20not%20burger-menu%20768px.png)
***
**app burger-menu open 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/app%20burger-menu%20open%20320px.png)
***
**app burger-menu open 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/app%20burger-menu%20open%20768px.png)
***
**app.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/app.png)
***
**book-page comment collapse.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/book-page%20comment%20collapse.png)
***
**book-page comment expand.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/book-page%20comment%20expand.png)
***
**slider after 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20after%201440px.png)
***
**slider after 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20after%20320px.png)
***
**slider after 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20after%20768px.png)
***
**slider before 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20before%201440px.png)
***
**slider before 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20before%20320px.png)
***
**slider before 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20before%20768px.png)
***
**slider more two foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20more%20two%20foto%201440px.png)
***
**slider more two foto 320px (1).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20more%20two%20foto%20320px%20(1).png)
***
**slider more two foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20more%20two%20foto%20320px.png)
***
**slider more two foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20more%20two%20foto%20768px.png)
***
**slider not foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20not%20foto%201440px.png)
***
**slider not foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20not%20foto%20320px.png)
***
**slider not foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20not%20foto%20768px.png)
***
**slider one foto 1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20one%20foto%201440px.png)
***
**slider one foto 320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20one%20foto%20320px.png)
***
**slider one foto 768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/clevertecKress/1675882420/slider%20one%20foto%20768px.png)

2023-02-08 19:08 UTC, Ivan6813 approved these changes

2023-02-08 19:10 UTC, merged